### ISSUE TITLE
Compilation error. Missing histedit.h

### ISSUE THREAD

**Issue by olofk** [jbush001/NyuziToolchain#30]
[ 62%] Building CXX object tools/lldb/source/Core/CMakeFiles/lldbCore.dir/IOHandler.cpp.o
In file included from /home/olof/code/or1k/staging/NyuziToolchain/tools/lldb/source/Core/IOHandler.cpp:32:0:
/home/olof/code/or1k/staging/NyuziToolchain/tools/lldb/include/lldb/Host/Editline.h:48:22: fatal error: histedit.h: No such file or directory
 #include <histedit.h>
                      ^
compilation terminated.
tools/lldb/source/Core/CMakeFiles/lldbCore.dir/build.make:721: recipe for target 'tools/lldb/source/Core/CMakeFiles/lldbCore.dir/IOHandler.cpp.o' failed
make[2]: *** [tools/lldb/source/Core/CMakeFiles/lldbCore.dir/IOHandler.cpp.o] Error 1
CMakeFiles/Makefile2:11211: recipe for target 'tools/lldb/source/Core/CMakeFiles/lldbCore.dir/all' failed
make[1]: *** [tools/lldb/source/Core/CMakeFiles/lldbCore.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jbush001** [comment]
It sounds like libedit-dev is missing.

However, that this is only necessary for compiling lldb (the debugger), which is a bit experimental anyway. If you want to disable lldb in the build, I believe you can comment out the following line in tools/CMakeLists.txt:

    add_llvm_external_project(lldb)
