### ISSUE TITLE
Support for autovectorization

### ISSUE THREAD

**Issue by jbush001** [jbush001/NyuziToolchain#79]
- Add VectorProcTargetTransformInfo
- Currently commented out in https://github.com/jbush001/NyuziToolchain/blob/850e04ee68d66d4b5c0d1ff3a1c538f194f180c8/tools/clang/lib/Driver/ToolChains/Clang.cpp#L4064

**Comment by Hatelix** [comment]
Hi Jeff,
I'm currently working on this issue.

**Comment by jbush001** [comment]
Yep, thanks!
